// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'subscription.dart';
part 'convex_client.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `convert_value`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ConvexClientWrapper>>
abstract class ConvexClientWrapper implements RustOpaqueInterface {
  Future<void> connect({required String deploymentUrl});

  Future<ConvexValue> mutation({
    required String functionName,
    required List<(String, ConvexValue)> args,
  });

  factory ConvexClientWrapper() =>
      RustLib.instance.api.crateApiConvexClientConvexClientWrapperNew();

  Future<ConvexValue> query({
    required String functionName,
    required List<(String, ConvexValue)> args,
  });

  Future<ConvexSubscription> subscribe({
    required String functionName,
    required List<(String, ConvexValue)> args,
  });
}

class ConvexError implements FrbException {
  final String message;

  const ConvexError({required this.message});

  @override
  int get hashCode => message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConvexError &&
          runtimeType == other.runtimeType &&
          message == other.message;
}

@freezed
sealed class ConvexValue with _$ConvexValue {
  const ConvexValue._();

  const factory ConvexValue.null_() = ConvexValue_Null;
  const factory ConvexValue.string(String field0) = ConvexValue_String;
  const factory ConvexValue.int64(PlatformInt64 field0) = ConvexValue_Int64;
  const factory ConvexValue.float64(double field0) = ConvexValue_Float64;
  const factory ConvexValue.array(List<ConvexValue> field0) = ConvexValue_Array;
  const factory ConvexValue.object(Map<String, ConvexValue> field0) =
      ConvexValue_Object;
  const factory ConvexValue.bytes(Uint8List field0) = ConvexValue_Bytes;

  static ConvexValue fromBool({required bool value}) => RustLib.instance.api
      .crateApiConvexClientConvexValueFromBool(value: value);

  static ConvexValue fromDouble({required double value}) => RustLib.instance.api
      .crateApiConvexClientConvexValueFromDouble(value: value);

  static ConvexValue fromInt({required PlatformInt64 value}) =>
      RustLib.instance.api.crateApiConvexClientConvexValueFromInt(value: value);

  static ConvexValue fromString({required String value}) => RustLib.instance.api
      .crateApiConvexClientConvexValueFromString(value: value);

  static ConvexValue nullValue() =>
      RustLib.instance.api.crateApiConvexClientConvexValueNullValue();

  Future<String> toJsonString() => RustLib.instance.api
      .crateApiConvexClientConvexValueToJsonString(that: this);
}
